name: Arweave Deploy

# Trigger deployment only when pushing to the master branch
on:
  push:
    branches:
      - master

jobs:
  Arweave-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Verify that required secrets are present
      # DEPLOY_KEY: Your Arweave wallet key (required)
      # DEPLOY_ANT_PROCESS_ID: Your ArNS name's ANT process ID (required)
      # DEPLOY_UNDERNAME: Optional undername to deploy to
      - name: Check required secrets
        run: |
          if [ -z "$DEPLOY_KEY" ]; then
            echo "Error: DEPLOY_KEY secret is required but not set"
            exit 1
          fi
          if [ -z "$DEPLOY_ANT_PROCESS_ID" ]; then
            echo "Error: DEPLOY_ANT_PROCESS_ID secret is required but not set"
            exit 1
          fi
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_ANT_PROCESS_ID: ${{ secrets.DEPLOY_ANT_PROCESS_ID }}

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run the appropriate deploy script based on whether DEPLOY_UNDERNAME is set
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_ANT_PROCESS_ID: ${{ secrets.DEPLOY_ANT_PROCESS_ID }}
          DEPLOY_UNDERNAME: ${{ secrets.DEPLOY_UNDERNAME }}
        run: |
          if [ -n "$DEPLOY_UNDERNAME" ]; then
            echo "Deploying with undername: $DEPLOY_UNDERNAME"
            npm run deploy-undername
          else
            echo "Deploying without undername"
            npm run deploy
          fi
